config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about(/:name)' => 'pages#about', as: 'about'
  resources :posts
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include Sluggable
  validates_with CategoryValidator
end

app/models/concerns/sluggable.rb
module Sluggable

  extend ActiveSupport::Concern

  included do
    
    before_validation :set_default_slug, on: [:create, :update]
    validates :slug,
      format: { with: /\A[a-z0-9]+\z/, message: "スラグが無効です" },
      uniqueness: { message: "そのナメクジはすでに撮影されています" }

    private
    def set_default_slug
      if !self.title.nil? && !self.title.empty? && (self.slug.nil? || self.slug.empty?)
        self.slug = self.title.parameterize 
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  include Sluggable
  validates_with PostValidator

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :warning, :danger, :info
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @session = session[:user].inspect
    @categories = Category.all
  end

  def show
  end

  def edit
  end
  
  def update
    if @category.update(get_category_params) 
      redirect_to categories_path, info: "カテゴリーを編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, info: "カテゴリーを削除しました"
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(get_category_params)
    if category.valid?
      category.save
      redirect_to categories_path, info: "カテゴリーが作成されました"
    else
      @category = category
      render 'new'
    end
  end


  private
  def get_category_params
    params.require(:category).permit(:title, :slug)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
  def about
    @name = params[:name]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :edit, :show, :destroy]

  def index
    session[:user] = { username: "マクス", id: 4 }
    @posts = Post.all
    respond_to do |format|
      format.html
      format.json do
        render json: @posts.as_json(only: [:title, :created_at, :id])
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(get_post_params)
      redirect_to posts_path, info: "記事を編集しました"
    else
      render 'edit'
    end
  end
  
  def new
    @post = Post.new
  end
  
  def create
    post = Post.new(get_post_params)
    if post.valid?
      post.save
      redirect_to posts_path, info: "記事が作成されました"
    else
      @post = post
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, info: "記事を削除しました"
  end

  private
  def get_post_params
    params.require(:post).permit(:title, :slug, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1 class="title">カテゴリを編集</h1>

<% if @category.errors.any? %>
<% @category.errors.full_messages.each do |msg| %>
<div class="notification is-danger">
  <button class="delete"></button>
  <%= msg %>
</div>
<% end %>
<% end %>

<%= form_for @category do |f| %>
<div class="field">
  <label class="label">名</label>
  <div class="control">
    <%= f.text_field :title, class: 'input' %>
  </div>
</div>
<div class="field">
  <label class="label">リンク</label>
  <div class="control">
    <%= f.text_field :slug, class: 'input' %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.submit "提出する", class: 'button is-success is-outlined' %>
  </div>
</div>
<% end %>

app/views/categories/index.html.erb
<div class="categories">
  <div class="categories-header">
    <h1 class="title categories-header-title">カテゴリー</h1>
    <a href="<%= new_category_path %>" class="button is-primary is-outlined categories-header-add">
      <span class="icon">
        <i class="fas fa-plus"></i>
      </span>
      <span>新たなカテゴリー</span>
    </a>
  </div>
</div>
<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th>ID</th>
      <th>名</th>
      <th>行動</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |cat| %>
    <tr>
      <td><%= cat.id %></td>
      <td><a href="<%= category_path(cat.id) %>"><%= cat.title %></a></td>
      <td class="categories-actions">
        <a href="<%= edit_category_path(cat.id) %>" class="has-text-dark">
          <span class="icon">
            <i class="fas fa-edit"></i>
          </span>
        </a>
        <a href="<%= category_path(cat.id) %>" data-method="DELETE" class="has-text-danger">
          <span class="icon">
            <i class="fas fa-trash"></i>
          </span>
        </a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1 class="title">新たなカテゴリー</h1>

<% if @category.errors.any? %>
<% @category.errors.full_messages.each do |msg| %>
<div class="notification is-danger">
  <button class="delete"></button>
  <%= msg %>
</div>
<% end %>
<% end %>

<%= form_for @category do |f| %>
<div class="field">
  <label class="label">名</label>
  <div class="control">
    <%= f.text_field :title, class: 'input', placeholder: 'カテゴリー名' %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.submit "提出する", class: 'button is-success is-outlined' %>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ror</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= root_path %>">
        <span>すごいルビ</span>
        <span class="icon" class="has-text-danger">
          <i class="fas fa-gem"></i>
        </span>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="<%= about_path %>">
          について
        </a>
        <a class="navbar-item" href="<%= posts_path %>">
          ブログ
        </a>
        <a class="navbar-item" href="<%= categories_path %>">
          カテゴリー
        </a>
      </div>
    </div>
  </nav>

  <section class="section">
    <div class="container">
      <% flash.each do |name, msg| %>
      <div class="notification is-<%= name %>">
        <button class="delete"></button>
        <%= msg %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </section>
</body>

</html>

app/views/pages/about.html.erb
<h1 class="title">今日は <%= @name %></h1>
<p class="subtitle">何だかとうとう教育が根ざしうているですのに聞きたない。</p>

app/views/pages/home.html.erb
<h1 class="title">今日は世界</h1>
<p class="subtitle">
  それも今もっともその講演帰りって事の以上を集っならたろ。あたかも十月に意見国はまあこの授業ないないかもが聞かていたには記念訊かませありて、そうにも炙っんたますた。程度からしよごとくのもいよいよ結果がそんなにならでしょない。</p>

app/views/posts/edit.html.erb
<h1 class="title">記事を編集</h1>

<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="notification is-danger">
  <button class="delete"></button>
  <%= msg %>
</div>
<% end %>
<% end %>

<%= form_for @post do |f| %>
<div class="field">
  <label class="label">タイトル</label>
  <div class="control">
    <%= f.text_field :title, class: 'input' %>
  </div>
</div>
<div class="field">
  <label class="label">ナメクジ</label>
  <div class="control">
    <%= f.text_field :slug, class: 'input' %>
  </div>
</div>
<div class="field">
  <label class="label">コンテンツ</label>
  <div class="control">
    <%= f.text_area :content, class: 'textarea', rows: 10 %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.submit "編集する", class: 'button is-success is-outlined' %>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<h1 class="title is-size-1">最新の記事</h1>
<a href="<%= new_post_path %>" class="button is-primary is-outlined">
  <span class="icon">
    <i class="fas fa-plus"></i>
  </span>
  <span>新たな記事を書く</span>
</a>
<div class="posts">
  <% @posts.each do |post| %>
  <div class="card">
    <header class="card-header">
      <h2 class="card-header-title"><%= post.title %></h2>
      <a href="<%= edit_post_path(post.id) %>" class="card-header-icon" aria-label="edit">
        <span class="icon">
          <i class="fas fa-edit"></i>
        </span>
      </a>
      <a href="<%= post_path(post.id) %>" class="card-header-icon has-text-danger" aria-label="delete"
        data-method="DELETE">
        <span class="icon">
          <i class="fas fa-trash"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        <p><%= post.content.slice(0..200) %><% if post.content.length >= 200 %>...<% end %></p>
      </div>
    </div>
    <footer class="card-footer">
      <div class="card-footer-item">
        <a href="<%= post_path(post.id) %>" class="button is-info is-outlined">続きを読む</a>
      </div>
    </footer>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="title">新たな記事</h1>

<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="notification is-danger">
  <button class="delete"></button>
  <%= msg %>
</div>
<% end %>
<% end %>

<%= form_for @post do |f| %>
<div class="field">
  <label class="label">タイトル</label>
  <div class="control">
    <%= f.text_field :title, class: 'input' %>
  </div>
</div>
<div class="field">
  <label class="label">コンテンツ</label>
  <div class="control">
    <%= f.text_area :content, class: 'textarea', rows: 10 %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.submit "公開する", class: 'button is-success is-outlined' %>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<h1 class="title"><%= @post.title %></h1>
<p><%= @post.content %></p>
<a href="<%= posts_path %>" class="button is-dark is-outlined">View all posts</a>